<?php
$product=array();
$product[]=array(
    "id"=>1,
    "name"=>"Asus",
    "price"=>"1233300"
);
$product[]=array(
    "id"=>2,
    "name"=>"Dell",
    "price"=>"1633300"
);
$product[]=array(
    "id"=>3,
    "name"=>"Acer",
    "price"=>"140000"
);
$product[]=array(
    "id"=>4,
    "name"=>"Macbook",
    "price"=>"1933300"
);
$product[]=array(
    "id"=>5,
    "name"=>"MSI",
    "price"=>"2033300"
);